import { clearActors, loadExample } from './browser-start.mjs';
import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
await mkdir('qa', { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
const errors = []; page.on('pageerror', e => errors.push(e.message));
await page.goto('http://127.0.0.1:5173/shared-billing/');
await clearActors(page);
await page.waitForFunction(() => !document.querySelector('.example-card button')?.disabled, { timeout: 30000 });
await page.screenshot({ path: 'qa/empty.png' });
await loadExample(page);
await page.getByRole('button', { name: 'John Goodman, show linking films. Drag to pin.', exact: true }).waitFor();
await page.screenshot({ path: 'qa/bridges.png' });
await page.getByRole('button', { name: 'John Goodman, show linking films. Drag to pin.', exact: true }).click();
await page.getByRole('heading', { name: 'John Goodman', exact: true }).waitFor();
await page.screenshot({ path: 'qa/evidence.png' });
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Remove Audrey Hepburn', exact: true }).click();
const search = page.getByRole('combobox', { name: 'Search for an actor' });
await search.fill('Meg Ryan');
await page.getByRole('option').filter({ hasText: 'Meg Ryan' }).first().waitFor();
await search.press('Enter');
await page.getByRole('button', { name: '3 shared films', exact: true }).waitFor();
await page.getByRole('button', { name: '3 shared films', exact: true }).click();
await page.getByRole('link', { name: 'Sleepless in Seattle', exact: true }).waitFor();
await page.screenshot({ path: 'qa/direct.png' });
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Remove Meg Ryan', exact: true }).click();
await search.fill('Billy Crystal');
await page.getByRole('option').filter({ hasText: 'Billy Crystal' }).first().waitFor();
await search.press('Enter');
await page.locator('.overflow .node-button').waitFor();
await page.screenshot({ path: 'qa/crowded.png' });
await page.locator('.overflow .node-button').click();
await page.getByRole('heading', { name: 'Tom Hanks and Billy Crystal' }).waitFor();
await page.getByRole('button', { name: /^Show all/ }).click();
await page.getByText('All co-stars are now shown in the graph.').waitFor();
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Switch to dark mode' }).click();
await page.screenshot({ path: 'qa/dark.png' });
const chosen = page.getByRole('button', { name: 'Tom Hanks, chosen actor. Drag to pin.' });
const box = await chosen.boundingBox();
await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 80, box.y + box.height / 2 - 40, { steps: 5 }); await page.mouse.up();
if (await page.getByRole('button', { name: 'Reset layout' }).isDisabled()) throw new Error('Drag did not pin the actor');
await page.getByRole('button', { name: 'Reset layout' }).click();
if (!(await page.getByRole('button', { name: 'Reset layout' }).isDisabled())) throw new Error('Reset did not release the actor');
if (errors.length) throw new Error(errors.join('\n'));
console.log('Browser checks passed: example, bridge evidence, keyboard search, direct films, overflow expansion, dark mode, dragging and reset.');
await browser.close();
