import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('console', msg => console.log('console:', msg.type(), msg.text()));
page.on('pageerror', e => console.log('error:', e.message));
page.on('requestfailed', r => console.log('request failed:', r.url(), r.failure()));
page.on('response', r => { if (!r.ok()) console.log('response:', r.status(), r.url()); });
await page.goto('http://127.0.0.1:5173/shared-billing/');
await page.waitForTimeout(8000);
console.log(await page.locator('body').innerText());
await page.screenshot({ path: 'qa/boot.png' });
await browser.close();
