// A deliberate mix of familiar film stars across generations. Credit count alone
// would recommend prolific supporting performers rather than recognizable names.
export const recommendedActors = new Set([
  'Tom Hanks', 'Audrey Hepburn', 'Denzel Washington', 'Meryl Streep',
  'Leonardo DiCaprio', 'Kate Winslet', 'Brad Pitt', 'Angelina Jolie',
  'George Clooney', 'Julia Roberts', 'Sandra Bullock', 'Keanu Reeves',
  'Morgan Freeman', 'Samuel L. Jackson', 'Harrison Ford', 'Carrie Fisher',
  'Robert De Niro', 'Al Pacino', 'Dustin Hoffman', 'Jack Nicholson',
  'Anthony Hopkins', 'Jodie Foster', 'Michael Caine', 'Helen Mirren',
  'Judi Dench', 'Maggie Smith', 'Robin Williams', 'Whoopi Goldberg',
  'Eddie Murphy', 'Steve Martin', 'Billy Crystal', 'Bill Murray',
  'Meg Ryan', 'Michelle Pfeiffer', 'Susan Sarandon', 'Geena Davis',
  'Tom Cruise', 'Nicole Kidman', 'Will Smith', 'Charlize Theron',
  'Matt Damon', 'Ben Affleck', 'Christian Bale', 'Natalie Portman',
  'Scarlett Johansson', 'Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth',
  'Mark Ruffalo', 'Jeremy Renner', 'Chris Pratt', 'Zoe Saldana',
  'Ryan Reynolds', 'Ryan Gosling', 'Emma Stone', 'Emma Watson',
  'Jennifer Lawrence', 'Anne Hathaway', 'Hugh Jackman', 'Reese Witherspoon',
  'Cate Blanchett', 'Amy Adams', 'Viola Davis', 'Octavia Spencer',
  'Lupita Nyong\'o', 'Daniel Kaluuya', 'Michael B. Jordan', 'Idris Elba',
  'Florence Pugh', 'Saoirse Ronan', 'Timothée Chalamet', 'Zendaya',
  'Pedro Pascal', 'Oscar Isaac', 'Adam Driver', 'Margot Robbie',
  'Cillian Murphy', 'Emily Blunt', 'Jenna Ortega', 'Paul Mescal',
  'Kevin Bacon', 'John C. Reilly', 'Willem Dafoe', 'Jeff Bridges',
  'Kurt Russell', 'Sigourney Weaver', 'Jamie Lee Curtis', 'Michael Keaton',
  'Danny DeVito', 'John Travolta', 'Diane Keaton', 'Goldie Hawn',
  'Clint Eastwood', 'Robert Redford', 'Paul Newman', 'Elizabeth Taylor',
  'Cary Grant', 'James Stewart', 'Humphrey Bogart', 'Ingrid Bergman',
  'Marilyn Monroe', 'Grace Kelly', 'Sidney Poitier', 'Gregory Peck',
  'Bette Davis', 'Katharine Hepburn', 'Marlon Brando', 'Debbie Reynolds',
  'Jackie Chan', 'Michelle Yeoh', 'Jet Li', 'Bruce Lee',
  'Shah Rukh Khan', 'Aamir Khan', 'Amitabh Bachchan', 'Deepika Padukone',
  'Penélope Cruz', 'Javier Bardem', 'Antonio Banderas', 'Salma Hayek',
]);
